default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", ENV["USER"]) %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: doc_renamer_development

test:
  <<: *default
  database: doc_renamer_test

production:
  <<: *default
  database: doc_renamer_production
  username: doc_renamer
  password: <%= ENV["DOC_RENAMER_DATABASE_PASSWORD"] %>
